---

- name: copy my.cnf
  template:
          src: my.cnf.j2
          dest: "{{ mysql_config_file }}"
          owner: root
          group: root
          mode: 0644
  notify: restart mysql
  
- name: Verify mysql include directory exists.
  file:
          path: "{{ mysql_config_include_dir }}"
          state: directory
          owner: root
          group: root
          mode: 0755
  when: mysql_config_include_files | length

- name: Create slow query log file
  file:
          path: "{{ mysql_slow_query_log_file }}"
          state: touch
          owner: mysql
          group: mysql
          mode: 0640
  when: mysql_slow_query_log_enabled

- name: Create datadir of MySQL
  file:
         path: "{{ mysql_datadir }}"
         state: directory
         owner: mysql
         group: mysql
         mode: 0755
         setype: mysqld_db_t

- name: Create error log file
  file:
         path: "{{ mysql_log_error }}"
         state: touch
         owner: mysql
         group: mysql
         mode: 0640
  when:
    - mysql_log | default(true)
    - mysql_log_error | default(false)

- name: Ensure MySQL is started and enabled
  service:
         name: "{{ mysql_daemon }}"
         state: started
         enabled: true
  register: mysql_service_configuration

